### ISSUE TITLE
can't open ymt files

### ISSUE THREAD

**Issue by YisusOnDev** [grzybeek/YMTEditor#1]
I'm trying to open ymt files created with gtautil but i can't open it with YMTEditor.

Attached the 2 ymt files: 
[mp_myf_freemode.zip](https://github.com/grzybeek/YMTEditor/files/6758994/mp_myf_freemode.zip)

**Comment by grzybeek** [comment]
That's because you have defined props which are not added into YMTEditor
"unk_604819740", "unk_2358626934", "p_lfoot", "p_rfoot", "p_hip", "p_lhand", "p_rhand", "p_mouth" - are all these are even working in game? I don't know how gtautil generates ymt's but it shouldn't add these, I've never seen in GTA that any of these is used somewhere
