### ISSUE TITLE
shoe heels

### ISSUE THREAD

**Issue by LalinDurukan** [grzybeek/YMTEditor#18]
does not raise the character off the ground, even though I adjusted the heels correctly. the shoes are smooth, but they go under the ground. I did it according to the post in the forum but this is the problem.

**Comment by MarcT** [comment]
This is not an error in YMT editor but with your configuration on your addon/replace mod.
When I first got into working with YMT editor I ran into this issue myself. 
![image](https://github.com/grzybeek/YMTEditor/assets/109933/78df665c-62a1-4672-8082-20d1ca4e658b)
On the left you have an addon heal applied to a character, with the proper setting in YMT editor the character gets "lifted" for the heal.
The next image I applied a base game hat to the character, notice how the feet went flat, this was because I was missing a file. We will get there in a second.
Third image is me applying a base game heel, and 4th is me putting my addon heel back on. I had reached out t o grzybeek about this issue. I then discovered my issue was that I did not properly call the creaturemetadata file in my META. I instead was calling to a base game creaturemetadata file.

https://forum.cfx.re/t/how-to-create-addon-heels-or-hide-hair-with-addon-hat/4209989

In this guide you need to have 1.0 for heels under the metadata. I have come across a few platforms that require 1.5, but its rare. You also have to save a creaturemetadata ymt file.

You then have to add this line with your creaturemetadata file name to your shop meta file.
![image](https://github.com/grzybeek/YMTEditor/assets/109933/3b74cdd3-3ed2-484f-a833-87c88e7842bf)

Running without this, or pointing to the incorrect one (which is what I had done originally), causes the issue you are reporting. It is not an error of YMT editor.

**Comment by LalinDurukan** [comment]
I don't have a shop.meta file, or I haven't created one. how can I do this.

**Comment by LalinDurukan** [comment]
also I am not attaching this as an attachment, my file extension is like this; "mp_f_freemode_01^feet_070_u"

I kept adding to an already existing ymt.

**Comment by LalinDurukan** [comment]
the strange thing is that there is nothing wrong with my shoes. my heels look good, there is no warping. but the character doesn't rise. the heels stay below the floor.

**Comment by grzybeek** [comment]
This issue is not related to YMTEditor itself, probably user error in setup.
